name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Build
        run: npm run build
      - name: Chrome Test
        run: npm test -- --project=chromium
      - name: Firefox Test
        run: npm test -- --project=firefox
      - name: WebKit Test
        run: npm test -- --project=webkit
      - uses: actions/upload-artifact@v4
        with:
          name: turbo-modal-dialog-dist
          path: dist/*
